services:
  xysbtn-pg:
    image: postgres
    container_name: xysbtn-pg
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=xysbtn
      - POSTGRES_PASSWORD=m6MOjZzM
      - POSTGRES_DB=xysbtn_db
    ports:
      - 5432:5432
    restart: always
    volumes:
      - /root/xysbtn/xysbtn_upload/db:/var/lib/postgresql/data
  xysbtn-upload:
    build:
      context: ./
      dockerfile: Dockerfile
    image: xysbtn-upload
    container_name: xysbtn-upload
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - xysbtn-pg
    links:
      - xysbtn-pg
    volumes:
      - /root/xysbtn/xysbtn_upload/certs:/app/certs
      - /root/xysbtn/xysbtn_upload/secret.pub:/app/secret.pub
      - /root/xysbtn/voice:/app/voices
