name: Build & Deploy to Aliyun
on:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: xysbtn-upload docker run
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.PRAVITE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al